#!/bin/bash
#
# Send coverage data to coveralls.io
#
# `go test -coverprofile=` only supports generating a coverage profile for one
# package at a time. This script combines coverage data from multiple packages
# and then sends the coverage data to coveralls.io
#
echo "mode: set" > acc.out
FAIL=0

packages="$(find . -type d -maxdepth 3 \
	! -path './.git*' \
	! -path '*/_*' \
	! -path './Godeps*' \
	! -path './test*' \
  ! -path './vendor*' \
)"

# Standard go tooling behavior is to ignore dirs with leading underscores
for dir in $packages;
do
  if ls $dir/*.go &> /dev/null; then
    go test -coverprofile=profile.out $dir || FAIL=$?
    if [ -f profile.out ]
    then
      cat profile.out | grep -v "mode: set" | grep -v "mocks.go" >> acc.out
      rm profile.out
    fi
  fi
done

# Failures have incomplete results, so don't send
if [ "$FAIL" -eq 0 ]; then
  goveralls -service=travis-ci -v -coverprofile=acc.out
fi

rm -f acc.out

exit $FAIL
