// @generated Code generated by thrift-gen. Do not modify.

// Package pingpong is generated code used to make or handle TChannel calls using Thrift.
package pingpong

import (
	"fmt"

	athrift "github.com/apache/thrift/lib/go/thrift"
	"github.com/uber/tchannel-go/thrift"
)

// Interfaces for the service and client for the services defined in the IDL.

// TChanPingPong is the interface that defines the server handler and client interface.
type TChanPingPong interface {
	Ping(ctx thrift.Context, request *Ping) (*Pong, error)
}

// Implementation of a client and service handler.

type tchanPingPongClient struct {
	thriftService string
	client        thrift.TChanClient
}

func NewTChanPingPongInheritedClient(thriftService string, client thrift.TChanClient) *tchanPingPongClient {
	return &tchanPingPongClient{
		thriftService,
		client,
	}
}

// NewTChanPingPongClient creates a client that can be used to make remote calls.
func NewTChanPingPongClient(client thrift.TChanClient) TChanPingPong {
	return NewTChanPingPongInheritedClient("PingPong", client)
}

func (c *tchanPingPongClient) Ping(ctx thrift.Context, request *Ping) (*Pong, error) {
	var resp PingPongPingResult
	args := PingPongPingArgs{
		Request: request,
	}
	success, err := c.client.Call(ctx, c.thriftService, "Ping", &args, &resp)
	if err == nil && !success {
		switch {
		case resp.PingError != nil:
			err = resp.PingError
		default:
			err = fmt.Errorf("received no result or unknown exception for Ping")
		}
	}

	return resp.GetSuccess(), err
}

type tchanPingPongServer struct {
	handler TChanPingPong
}

// NewTChanPingPongServer wraps a handler for TChanPingPong so it can be
// registered with a thrift.Server.
func NewTChanPingPongServer(handler TChanPingPong) thrift.TChanServer {
	return &tchanPingPongServer{
		handler,
	}
}

func (s *tchanPingPongServer) Service() string {
	return "PingPong"
}

func (s *tchanPingPongServer) Methods() []string {
	return []string{
		"Ping",
	}
}

func (s *tchanPingPongServer) Handle(ctx thrift.Context, methodName string, protocol athrift.TProtocol) (bool, athrift.TStruct, error) {
	switch methodName {
	case "Ping":
		return s.handlePing(ctx, protocol)

	default:
		return false, nil, fmt.Errorf("method %v not found in service %v", methodName, s.Service())
	}
}

func (s *tchanPingPongServer) handlePing(ctx thrift.Context, protocol athrift.TProtocol) (bool, athrift.TStruct, error) {
	var req PingPongPingArgs
	var res PingPongPingResult

	if err := req.Read(protocol); err != nil {
		return false, nil, err
	}

	r, err :=
		s.handler.Ping(ctx, req.Request)

	if err != nil {
		switch v := err.(type) {
		case *PingError:
			if v == nil {
				return false, nil, fmt.Errorf("Handler for pingError returned non-nil error type *PingError but nil value")
			}
			res.PingError = v
		default:
			return false, nil, err
		}
	} else {
		res.Success = r
	}

	return err == nil, &res, nil
}
