// Autogenerated by Thrift Compiler (1.0.0-dev)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package remoteservice

import (
	"bytes"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"github.com/uber/ringpop-go/test/remoteservice/.gen/go/shared"
	"github.com/uber/ringpop-go/test/remoteservice/.gen/go/unused"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = shared.GoUnusedProtection__
var _ = unused.GoUnusedProtection__
var GoUnusedProtection__ int
