name: Build and Test

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    name: Run tests
    
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
        
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
        
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/uber/ringpop-go
        
    - name: Debug
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}
      env:
        GOPATH: /home/runner/work/ringpop-go/go
        
    - name: Install dependencies
      run: |
        go get -u github.com/Masterminds/glide
        go get github.com/axw/gocov/gocov
        go get github.com/mattn/goveralls
        go get golang.org/x/tools/cmd/cover
        python -m pip install --upgrade pip
        pip install virtualenv
        /home/runner/work/ringpop-go/go/github.com/uber/ringpop-go/scripts/travis/get-thrift.sh
        /home/runner/work/ringpop-go/go/github.com/uber/ringpop-go/scripts/travis/get-thrift-gen.sh
        /home/runner/work/ringpop-go/go/github.com/uber/ringpop-go/scripts/travis/get-cram.sh
        npm install -g tcurl@v4.22.2
        
    - name: Run Setup
      run: make setup
      
#    - name: Lint
#      run: make lint
      
    - name: Unit Tests
      run: make test-unit
      env:
        GOPATH: /home/runner/work/ringpop-go/go
     
    - name: Race Tests
      run: make test-examples
     
    - name: Example Tests
      run: make test-race
      
    - name: Code Coverage
      run: make coveralls
